<a href="https://colab.research.google.com/github/suganthavk-ai/-Social-Media-Engagement-Analysis/blob/main/Social_Media_Engagement_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **📊 Social Media Engagement Analysis**

**Dataset Provided:**
social_media_engagement_5000.csv

# **Task 1 — Data Import & Setup**

1.1 Import CSV using Pandas

1.2 Check/convert data types

1.3 Convert date columns to datetime

In [1]:
!pip install matplotlib seaborn plotly.express pandas numpy

Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Collecting plotly.express
  Downloading plotly_express-0.4.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: plotly>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from plotly.express) (5.24.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from plotly.express) (0.15.0)
Requirement already satisfied: scipy>=0.18 in /usr/local/lib/python3.13/dist-packages (from plotly.express) (1.16.3)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.13/dist-packages (from plotly.express) (1.0.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly>=4.1.0->plotly.express) (9.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.9.0->plotly.express) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.9.0->plotly.express) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.9.0->plotly.express) (2.25.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.9.0->plotly.express) (4.16.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.9.0->plotly.express) (2.4.0)
Downloading plotly_express-0.4.1-py2.py3-none-any.whl (2.9 kB)
Installing collected packages: plotly.express
Successfully installed plotly.express-0.4.1

In [2]:
# Data Import & Setup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
# Load CSV file
#https://github.com/GeethaGunasekaran1/Dataset_rep/blob/main/social_media_engagement_5000.csv

df=pd.read_csv("https://raw.githubusercontent.com/GeethaGunasekaran1/Dataset_rep/main/social_media_engagement_5000.csv")
df.head()

,user_id,age,gender,country,post_id,post_type,post_category,likes,comments,shares,watch_time_sec,impression_count,posted_at,follower_count,is_verified,device_type,sentiment,hashtags,engagement_rate
0,25795,43.0,Female,Brazil,496713,image,fitness,7011.0,354.0,1157.0,5726,44650,17-12-2022,81734,False,mobile,negative,#foodie #travel #love,0.190862
1,10860,33.0,Male,Brazil,157326,reel,food,11750.0,2606.0,1807.0,5947,80216,02-06-2023,5963,False,mobile,negative,#fitness,0.201493
2,86820,32.0,Female,UK,109864,text,food,4862.0,344.0,955.0,6946,44858,07-05-2023,501783,False,tablet,positive,#foodie,0.137345
3,64886,51.0,Other,France,848877,text,fitness,5350.0,1083.0,1049.0,229,70455,12-02-2023,480212,False,mobile,negative,#music #foodie #fun,0.106195
4,16265,34.0,Other,UK,449706,image,fitness,12682.0,2735.0,1300.0,4798,6019,23-05-2023,383936,False,mobile,negative,#travel,2.777372

# **Check dataset structure**

In [4]:
print("Shape:",df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

Shape: (5000, 19)

Columns:
['user_id', 'age', 'gender', 'country', 'post_id', 'post_type', 'post_category', 'likes', 'comments', 'shares', 'watch_time_sec', 'impression_count', 'posted_at', 'follower_count', 'is_verified', 'device_type', 'sentiment', 'hashtags', 'engagement_rate']

Data Types:
user_id               int64
age                 float64
gender               object
country              object
post_id               int64
post_type            object
post_category        object
likes               float64
comments            float64
shares              float64
watch_time_sec        int64
impression_count      int64
posted_at            object
follower_count        int64
is_verified            bool
device_type          object
sentiment            object
hashtags             object
engagement_rate     float64
dtype: object

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           5000 non-null   int64
 1   age               4850 non-null   float64
 2   gender            4850 non-null   object
 3   country           5000 non-null   object
 4   post_id           5000 non-null   int64
 5   post_type         5000 non-null   object
 6   post_category     5000 non-null   object
 7   likes             4850 non-null   float64
 8   comments          4850 non-null   float64
 9   shares            4850 non-null   float64
 10  watch_time_sec    5000 non-null   int64
 11  impression_count  5000 non-null   int64
 12  posted_at         5000 non-null   object
 13  follower_count    5000 non-null   int64
 14  is_verified       5000 non-null   bool
 15  device_type       5000 non-null   object
 16  sentiment         4850 non-null   object
 17  hashtags          5000 non-null   object
 18  engagement_rate   5000 non-null   float64
dtypes: bool(1), float64(5), int64(5), object(8)
memory usage: 708.1+ KB

In [5]:
# Check missing values

df.isnull().sum()

user_id               0
age                 150
gender              150
country               0
post_id               0
post_type             0
post_category         0
likes               150
comments            150
shares              150
watch_time_sec        0
impression_count      0
posted_at             0
follower_count        0
is_verified           0
device_type           0
sentiment           150
hashtags              0
engagement_rate       0
dtype: int64

# **Task 2 — Data Cleaning**

**2.1 Cleaning Missing Data**

■ Detect missing values (isnull(), isna())

■ Handle using: dropna(), fillna(), median/mode, forward/backward-fill

**2.2 Duplicate Handling**

Identify & remove duplicates

**2.3 Data Formatting**

■ Fix incorrect data types

■ Standardize categories (e.g., gender labels)

■ Correct unrealistic values in likes, comments, shares

**2.4 Feature Cleaning**

■ Extract hashtag count

■ Clean sentiment labels

In [6]:
# Total missing Values

print(df.isnull().sum())

#Total missing values in entire dataset
print("Total Missing Values: ",df.isnull().sum().sum())

user_id               0
age                 150
gender              150
country               0
post_id               0
post_type             0
post_category         0
likes               150
comments            150
shares              150
watch_time_sec        0
impression_count      0
posted_at             0
follower_count        0
is_verified           0
device_type           0
sentiment           150
hashtags              0
engagement_rate       0
dtype: int64
Total Missing Values:  900

In [7]:
from pandas.core.arrays import categorical
# Handle Missing Values by identifing numeric and category columns:

numeric_colm = df.select_dtypes(include=np.number).columns
categorical_colm = df.select_dtypes(include="object").columns

print("Numeric Columns: ")
print(numeric_colm)

print("\nCategorical Columns: ")
print(categorical_colm)

Numeric Columns:
Index(['user_id', 'age', 'post_id', 'likes', 'comments', 'shares',
       'watch_time_sec', 'impression_count', 'follower_count',
       'engagement_rate'],
      dtype='object')

Categorical Columns:
Index(['gender', 'country', 'post_type', 'post_category', 'posted_at',
       'device_type', 'sentiment', 'hashtags'],
      dtype='object')

In [8]:
# Fill numeric missing values with median
for col in numeric_colm:
    df[col] = df[col].fillna(df[col].median())

In [9]:
# Fill categorical missing values with mode

for col in categorical_colm:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum()

user_id             0
age                 0
gender              0
country             0
post_id             0
post_type           0
post_category       0
likes               0
comments            0
shares              0
watch_time_sec      0
impression_count    0
posted_at           0
follower_count      0
is_verified         0
device_type         0
sentiment           0
hashtags            0
engagement_rate     0
dtype: int64

In [10]:
# Duplicate handling
# Check duplicates
print("Duplicate rows:", df.duplicated().sum())
# Remove duplicates:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Duplicate rows: 0
Shape after removing duplicates: (5000, 19)

In [11]:
# Data Formatting
# Convert date column

for col in df.select_dtypes(include="object").columns:
    print("\n", col)
    print(df[col].unique())

 gender
['Female' 'Male' 'Other']

 country
['Brazil' 'UK' 'France' 'Canada' 'Japan' 'Australia' 'India' 'UAE'
 'Germany' 'USA']

 post_type
['image' 'reel' 'text' 'video']

 post_category
['fitness' 'food' 'tech' 'travel' 'fashion' 'lifestyle' 'education'
 'music']

 posted_at
['17-12-2022' '02-06-2023' '07-05-2023' '12-02-2023' '23-05-2023'
 '16-09-2023' '15-04-2022' '20-12-2023' '06-07-2023' '16-11-2022'
 '15-02-2022' '29-08-2022' '27-09-2022' '29-10-2023' '20-09-2023'
 '06-02-2022' '24-07-2022' '01-05-2023' '20-04-2022' '14-11-2022'
 '15-08-2023' '17-03-2022' '02-09-2023' '13-05-2023' '24-04-2023'
 '24-01-2023' '11-08-2023' '16-08-2023' '30-12-2022' '05-11-2022'
 '04-03-2022' '24-09-2022' '02-02-2022' '09-02-2022' '17-11-2023'
 '17-09-2022' '23-10-2023' '13-08-2022' '18-01-2023' '01-10-2023'
 '05-01-2022' '22-03-2023' '15-10-2022' '27-02-2022' '13-03-2022'
 '11-11-2023' '25-06-2023' '23-03-2022' '10-09-2023' '04-10-2022'
 '06-06-2023' '28-07-2023' '16-05-2022' '24-04-2022' '06-06-2022'
 '31-01-2023' '17-08-2022' '04-09-2023' '12-09-2022' '28-06-2022'
 '02-01-2023' '31-01-2022' '18-04-2022' '09-10-2022' '13-09-2023'
 '25-01-2023' '13-06-2023' '08-02-2023' '19-06-2022' '24-06-2022'
 '15-03-2022' '30-03-2023' '24-05-2023' '28-08-2022' '06-04-2022'
 '29-05-2023' '21-07-2022' '01-04-2022' '21-08-2022' '21-10-2023'
 '10-09-2022' '06-01-2023' '25-12-2023' '20-03-2023' '17-03-2023'
 '05-03-2022' '20-10-2023' '01-02-2023' '09-09-2023' '26-11-2022'
 '02-07-2023' '27-05-2022' '19-02-2023' '15-12-2022' '31-12-2022'
 '20-02-2023' '17-09-2023' '22-05-2023' '07-06-2023' '07-12-2023'
 '07-09-2022' '06-09-2022' '26-09-2022' '24-03-2023' '24-03-2022'
 '11-02-2023' '05-12-2022' '21-03-2022' '05-04-2022' '16-09-2022'
 '02-05-2022' '04-05-2022' '19-06-2023' '29-12-2023' '16-10-2022'
 '07-04-2023' '02-04-2022' '24-01-2022' '17-04-2022' '21-02-2022'
 '12-12-2023' '21-10-2022' '27-10-2022' '11-12-2022' '17-01-2023'
 '22-07-2023' '13-07-2022' '11-07-2023' '12-03-2023' '20-01-2023'
 '07-01-2023' '27-08-2022' '27-01-2023' '10-10-2023' '12-10-2022'
 '13-01-2022' '21-11-2023' '20-10-2022' '14-09-2022' '04-08-2023'
 '19-11-2023' '02-07-2022' '18-06-2023' '22-06-2022' '18-12-2023'
 '28-03-2023' '16-04-2023' '22-03-2022' '17-11-2022' '03-02-2023'
 '07-07-2022' '14-03-2023' '15-04-2023' '24-06-2023' '06-04-2023'
 '30-05-2023' '25-08-2022' '30-06-2022' '14-02-2023' '31-05-2023'
 '01-07-2022' '14-04-2022' '29-09-2022' '14-10-2022' '28-03-2022'
 '21-01-2023' '14-03-2022' '26-08-2023' '16-11-2023' '06-11-2022'
 '30-11-2023' '19-03-2023' '24-08-2022' '05-11-2023' '08-08-2023'
 '18-08-2022' '11-09-2022' '21-12-2022' '10-05-2023' '18-07-2022'
 '05-03-2023' '20-04-2023' '08-12-2022' '19-04-2023' '02-03-2023'
 '14-02-2022' '09-12-2022' '22-11-2023' '17-01-2022' '07-08-2022'
 '19-08-2023' '10-07-2022' '26-01-2023' '15-03-2023' '06-10-2023'
 '12-05-2023' '04-04-2022' '27-11-2023' '06-12-2022' '26-12-2022'
 '22-04-2022' '30-10-2022' '20-02-2022' '02-12-2023' '21-12-2023'
 '08-10-2022' '23-04-2022' '05-02-2022' '15-09-2023' '14-11-2023'
 '19-03-2022' '31-10-2022' '16-10-2023' '15-01-2022' '02-10-2023'
 '16-06-2022' '27-10-2023' '25-07-2023' '22-07-2022' '05-07-2023'
 '05-10-2022' '11-04-2022' '18-06-2022' '16-06-2023' '07-02-2023'
 '21-05-2022' '13-12-2022' '12-07-2022' '01-06-2022' '27-07-2022'
 '03-07-2023' '23-01-2023' '21-06-2022' '03-12-2022' '07-03-2023'
 '28-08-2023' '04-05-2023' '28-10-2023' '16-04-2022' '28-07-2022'
 '17-12-2023' '14-12-2022' '18-12-2022' '17-02-2022' '03-09-2022'
 '26-11-2023' '22-04-2023' '06-05-2022' '02-09-2022' '25-04-2023'
 '13-10-2023' '16-05-2023' '15-08-2022' '11-03-2022' '31-03-2023'
 '01-08-2023' '02-01-2022' '21-11-2022' '09-05-2022' '28-04-2023'
 '26-05-2022' '01-04-2023' '08-01-2022' '08-08-2022' '26-12-2023'
 '12-04-2022' '09-11-2023' '15-12-2023' '05-05-2023' '19-07-2022'
 '26-01-2022' '16-12-2022' '27-11-2022' '16-07-2022' '25-05-2023'
 '30-01-2022' '26-10-2022' '13-05-2022' '04-11-2022' '21-01-2022'
 '10-02-2022' '17-04-2023' '26-10-2023' '04-04-2023' '18-05-2023'
 '13-02-2022' '20-09-2022' '09-01-2022' '22-02-2022' '08-05-2022'
 '15-06-2023' '09-06-2023' '20-05-2022' '20-08-2022' '29-03-2022'
 '18-07-2023' '29-09-2023' '20-07-2022' '27-12-2022' '12-05-2022'
 '26-06-2022' '30-06-2023' '22-01-2022' '15-10-2023' '15-11-2022'
 '17-06-2022' '07-02-2022' '21-07-2023' '08-01-2023' '24-09-2023'
 '03-03-2023' '15-06-2022' '23-12-2023' '17-05-2023' '16-03-2022'
 '16-03-2023' '08-10-2023' '22-09-2022' '10-02-2023' '31-08-2022'
 '24-08-2023' '27-06-2023' '04-07-2023' '12-10-2023' '06-03-2023'
 '26-03-2023' '20-03-2022' '24-11-2022' '12-06-2022' '24-12-2022'
 '01-11-2023' '25-11-2022' '18-02-2023' '18-08-2023' '21-04-2023'
 '30-12-2023' '22-06-2023' '04-03-2023' '08-12-2023' '23-08-2023'
 '07-04-2022' '23-04-2023' '06-05-2023' '23-10-2022' '16-12-2023'
 '23-03-2023' '02-10-2022' '20-01-2022' '17-08-2023' '22-12-2022'
 '27-01-2022' '16-02-2022' '25-10-2023' '10-01-2023' '11-11-2022'
 '07-01-2022' '16-07-2023' '28-12-2022' '10-11-2023' '09-12-2023'
 '21-09-2022' '22-09-2023' '09-11-2022' '12-01-2023' '21-02-2023'
 '29-04-2023' '01-09-2023' '31-08-2023' '26-02-2022' '03-05-2022'
 '17-10-2022' '21-08-2023' '17-07-2023' '16-08-2022' '06-01-2022'
 '14-08-2023' '31-05-2022' '01-05-2022' '25-08-2023' '11-04-2023'
 '10-04-2023' '13-11-2023' '29-05-2022' '09-01-2023' '09-03-2023'
 '09-09-2022' '18-04-2023' '20-06-2023' '23-06-2023' '30-08-2023'
 '11-03-2023' '03-09-2023' '03-10-2022' '06-02-2023' '19-05-2023'
 '22-11-2022' '13-09-2022' '28-05-2023' '22-10-2022' '25-02-2022'
 '14-08-2022' '03-06-2023' '08-06-2022' '01-01-2023' '01-01-2022'
 '10-10-2022' '29-04-2022' '03-12-2023' '03-11-2022' '23-07-2023'
 '09-05-2023' '07-11-2022' '30-03-2022' '02-04-2023' '09-08-2023'
 '19-09-2022' '25-06-2022' '19-11-2022' '08-11-2023' '05-08-2022'
 '09-07-2022' '18-01-2022' '03-07-2022' '04-01-2023' '05-09-2022'
 '24-10-2023' '30-07-2023' '03-02-2022' '20-11-2022' '03-10-2023'
 '09-08-2022' '05-02-2023' '29-08-2023' '01-03-2022' '28-01-2023'
 '14-01-2022' '15-02-2023' '15-07-2022' '28-06-2023' '21-09-2023'
 '11-07-2022' '30-04-2023' '31-10-2023' '25-02-2023' '01-06-2023'
 '17-10-2023' '05-04-2023' '10-06-2023' '25-07-2022' '24-11-2023'
 '18-10-2022' '08-07-2023' '08-09-2023' '22-12-2023' '31-12-2023'
 '13-08-2023' '10-04-2022' '09-04-2023' '14-05-2023' '02-02-2023'
 '25-10-2022' '26-04-2022' '19-05-2022' '20-11-2023' '30-11-2022'
 '06-11-2023' '07-11-2023' '28-10-2022' '26-09-2023' '27-06-2022'
 '02-11-2023' '17-05-2022' '11-09-2023' '11-06-2022' '08-04-2023'
 '27-04-2023' '23-09-2023' '12-02-2022' '26-05-2023' '21-06-2023'
 '10-06-2022' '26-07-2022' '18-03-2023' '06-03-2022' '28-11-2023'
 '12-08-2022' '05-07-2022' '11-01-2022' '03-01-2022' '05-06-2023'
 '24-07-2023' '07-10-2022' '27-02-2023' '26-08-2022' '13-11-2022'
 '07-05-2022' '13-03-2023' '06-10-2022' '18-11-2023' '29-01-2022'
 '10-01-2022' '31-07-2022' '10-11-2022' '19-09-2023' '28-02-2023'
 '16-01-2022' '23-09-2022' '14-07-2023' '29-11-2022' '01-07-2023'
 '01-02-2022' '23-02-2022' '05-05-2022' '10-12-2022' '28-09-2022'
 '28-02-2022' '01-09-2022' '13-04-2022' '02-11-2022' '06-07-2022'
 '08-05-2023' '26-02-2023' '23-06-2022' '12-08-2023' '04-12-2022'
 '02-05-2023' '08-07-2022' '09-04-2022' '09-07-2023' '28-09-2023'
 '12-07-2023' '18-11-2022' '19-04-2022' '11-10-2023' '24-05-2022'
 '10-05-2022' '04-02-2023' '21-05-2023' '29-07-2022' '03-06-2022'
 '07-10-2023' '17-06-2023' '07-12-2022' '04-01-2022' '27-09-2023'
 '24-02-2023' '04-07-2022' '27-03-2022' '19-08-2022' '27-03-2023'
 '18-05-2022' '05-06-2022' '18-09-2022' '09-06-2022' '01-08-2022'
 '25-12-2022' '02-12-2022' '05-08-2023' '30-01-2023' '11-05-2022'
 '08-06-2023' '12-06-2023' '17-02-2023' '27-04-2022' '29-06-2022'
 '04-10-2023' '25-09-2023' '13-06-2022' '28-12-2023' '03-05-2023'
 '29-07-2023' '20-06-2022' '25-01-2022' '25-03-2023' '31-03-2022'
 '15-01-2023' '21-04-2022' '04-06-2022' '27-08-2023' '15-05-2023'
 '10-03-2022' '12-09-2023' '13-12-2023' '15-09-2022' '30-09-2022'
 '06-08-2023' '19-12-2022' '23-08-2022' '19-10-2022' '26-04-2023'
 '01-03-2023' '03-04-2022' '20-07-2023' '01-11-2022' '26-06-2023'
 '12-11-2023' '07-06-2022' '14-09-2023' '22-08-2022' '18-02-2022'
 '05-01-2023' '11-01-2023' '01-12-2022' '14-04-2023' '22-05-2022'
 '08-09-2022' '09-10-2023' '14-05-2022' '11-12-2023' '24-12-2023'
 '14-06-2022' '15-07-2023' '03-04-2023' '14-10-2023' '16-01-2023'
 '19-01-2022' '05-09-2023' '03-08-2023' '13-01-2023' '30-04-2022'
 '23-02-2023' '02-08-2023' '19-01-2023' '14-12-2023' '27-07-2023'
 '03-08-2022' '03-03-2022' '08-03-2022' '18-03-2022' '09-03-2022'
 '29-06-2023' '25-05-2022' '04-11-2023' '14-07-2022' '10-03-2023'
 '04-09-2022' '22-01-2023' '29-10-2022' '23-11-2023' '30-07-2022'
 '13-10-2022' '14-01-2023' '06-12-2023' '25-03-2022' '12-12-2022'
 '23-11-2022' '15-05-2022' '30-08-2022' '10-12-2023' '13-02-2023'
 '10-07-2023' '11-10-2022' '01-12-2023' '04-02-2022' '30-05-2022'
 '16-02-2023' '23-12-2022' '29-11-2023' '11-06-2023' '09-02-2023'
 '18-09-2023' '13-07-2023' '12-11-2022' '28-04-2022' '30-09-2023'
 '20-08-2023' '19-12-2023' '24-02-2022' '08-04-2022' '19-07-2023'
 '23-05-2022' '08-02-2022' '21-03-2023' '07-08-2023' '02-06-2022'
 '27-12-2023' '27-05-2023' '28-11-2022' '26-07-2023' '22-10-2023'
 '11-05-2023' '07-09-2023' '11-02-2022' '28-05-2022' '02-08-2022'
 '05-10-2023' '17-07-2022' '06-08-2022' '07-07-2023' '23-01-2022'
 '04-08-2022' '22-02-2023' '14-06-2023' '18-10-2023' '29-03-2023'
 '29-01-2023' '12-01-2022' '04-06-2023' '26-03-2022' '22-08-2023'
 '13-04-2023' '01-10-2022' '03-01-2023' '28-01-2022' '25-11-2023'
 '25-04-2022' '24-10-2022' '29-12-2022' '04-12-2023' '03-11-2023'
 '20-05-2023' '23-07-2022' '06-09-2023' '12-04-2023' '11-08-2022'
 '05-12-2023' '31-07-2023' '07-03-2022' '12-03-2022' '25-09-2022'
 '08-03-2023' '02-03-2022' '19-02-2022' '19-10-2023' '10-08-2022'
 '15-11-2023' '20-12-2022' '10-08-2023' '08-11-2022']

 device_type
['mobile' 'tablet' 'desktop']

 sentiment
['negative' 'positive' 'neutral']

 hashtags
['#foodie #travel #love' '#fitness' '#foodie' '#music #foodie #fun'
 '#travel' '#music' '#travel #music #fitness' '#music #fun #fitness'
 '#lifestyle #love' '#tech' '#fun #fashion #love' '#foodie #lifestyle'
 '#foodie #fashion' '#reels' '#foodie #fun #lifestyle'
 '#love #fashion #fitness' '#foodie #travel #fitness' '#foodie #fitness'
 '#fun' '#reels #fashion' '#fashion' '#fitness #love'
 '#foodie #tech #fitness' '#love #music' '#love #foodie' '#lifestyle'
 '#fashion #fitness #reels' '#reels #tech' '#tech #fitness'
 '#music #lifestyle #love' '#lifestyle #fun #music' '#fitness #tech'
 '#reels #foodie #travel' '#tech #fun #foodie' '#fun #reels'
 '#love #music #travel' '#foodie #music #love' '#fashion #foodie #love'
 '#tech #reels' '#love' '#tech #music #foodie' '#love #music #fitness'
 '#travel #fashion #reels' '#love #fitness' '#foodie #lifestyle #reels'
 '#reels #music #tech' '#music #fun' '#fitness #love #fun'
 '#fashion #reels #music' '#travel #music' '#reels #fitness #tech'
 '#lifestyle #reels #fitness' '#fun #fitness' '#fun #fashion #lifestyle'
 '#reels #travel' '#foodie #travel #fun' '#fashion #foodie #fitness'
 '#reels #tech #fun' '#fitness #foodie' '#music #foodie'
 '#reels #lifestyle' '#travel #fun' '#reels #love' '#music #reels'
 '#fitness #travel' '#music #travel #fashion' '#lifestyle #travel #foodie'
 '#lifestyle #music' '#fashion #fitness #love' '#tech #love'
 '#fashion #foodie' '#lifestyle #foodie #music' '#fitness #music #love'
 '#love #tech' '#music #love' '#music #travel #love' '#foodie #tech #love'
 '#music #tech #love' '#lifestyle #fitness' '#reels #love #travel'
 '#travel #lifestyle' '#fun #music #travel' '#tech #music #travel'
 '#fashion #travel' '#fitness #lifestyle' '#foodie #fashion #fun'
 '#tech #fitness #lifestyle' '#fashion #fun #fitness' '#tech #foodie'
 '#travel #reels' '#fashion #love' '#music #fashion #travel'
 '#travel #foodie' '#fun #fashion #music' '#fitness #love #travel'
 '#fun #travel #fitness' '#fun #foodie' '#fashion #lifestyle #foodie'
 '#love #music #lifestyle' '#love #music #tech' '#fun #tech #love'
 '#music #travel' '#lifestyle #fashion' '#fitness #music #reels'
 '#tech #foodie #love' '#lifestyle #fashion #foodie' '#lifestyle #foodie'
 '#fun #reels #lifestyle' '#travel #foodie #fun' '#music #reels #travel'
 '#fitness #foodie #reels' '#music #lifestyle #fashion'
 '#love #music #reels' '#fitness #love #reels' '#fashion #music'
 '#fun #travel' '#lifestyle #travel' '#fun #reels #travel' '#love #fun'
 '#music #lifestyle' '#fitness #reels #lifestyle' '#fun #tech'
 '#tech #music' '#fun #tech #reels' '#fun #fashion' '#fashion #fun'
 '#fun #love' '#travel #lifestyle #fitness' '#love #fashion'
 '#fun #lifestyle #fitness' '#fitness #foodie #love'
 '#lifestyle #foodie #travel' '#fashion #foodie #lifestyle' '#foodie #fun'
 '#reels #fitness' '#lifestyle #fun' '#fitness #foodie #lifestyle'
 '#fun #reels #fitness' '#reels #lifestyle #music' '#fitness #fun'
 '#fitness #love #fashion' '#fun #music' '#fashion #reels'
 '#love #lifestyle' '#fitness #fashion #foodie' '#music #tech #fitness'
 '#love #foodie #fitness' '#fitness #fashion' '#love #tech #reels'
 '#love #reels #music' '#fashion #tech' '#reels #foodie'
 '#travel #tech #music' '#fun #reels #music' '#foodie #fitness #music'
 '#foodie #tech' '#foodie #tech #travel' '#travel #fitness' '#love #reels'
 '#foodie #music' '#foodie #reels' '#love #fun #lifestyle'
 '#music #reels #lifestyle' '#fashion #love #travel'
 '#lifestyle #travel #love' '#travel #tech #reels' '#reels #love #tech'
 '#fun #reels #foodie' '#music #reels #fun' '#music #tech'
 '#lifestyle #fitness #tech' '#fun #foodie #fitness' '#love #fun #reels'
 '#fitness #reels' '#tech #fun #fitness' '#music #tech #foodie'
 '#love #travel #lifestyle' '#love #reels #tech' '#fun #reels #fashion'
 '#fun #fitness #lifestyle' '#reels #fun #music' '#tech #reels #travel'
 '#fashion #foodie #reels' '#travel #tech' '#fun #foodie #fashion'
 '#music #fun #fashion' '#reels #music #travel' '#foodie #fitness #love'
 '#travel #love' '#fun #tech #music' '#fun #fitness #reels'
 '#tech #fitness #reels' '#love #reels #lifestyle' '#travel #reels #love'
 '#fun #love #reels' '#love #lifestyle #travel' '#fun #love #travel'
 '#love #tech #foodie' '#travel #love #reels' '#fashion #foodie #fun'
 '#foodie #reels #fashion' '#love #fun #fashion' '#foodie #reels #love'
 '#fun #foodie #tech' '#tech #fun #reels' '#travel #fashion'
 '#fashion #travel #fun' '#lifestyle #travel #music'
 '#fitness #lifestyle #fashion' '#travel #tech #lifestyle'
 '#fun #music #foodie' '#foodie #reels #music' '#music #fitness'
 '#travel #music #love' '#fun #lifestyle' '#lifestyle #tech'
 '#fashion #fun #love' '#music #fitness #fun' '#reels #fun'
 '#music #fashion #foodie' '#travel #love #music'
 '#reels #fitness #foodie' '#music #fashion' '#fitness #fun #travel'
 '#love #travel #tech' '#travel #foodie #fitness' '#tech #fashion'
 '#lifestyle #reels' '#lifestyle #reels #love' '#fitness #music #fashion'
 '#travel #fun #lifestyle' '#fun #lifestyle #music' '#foodie #fun #love'
 '#fashion #fitness #lifestyle' '#foodie #music #fitness'
 '#tech #foodie #lifestyle' '#lifestyle #fashion #music'
 '#travel #fashion #foodie' '#foodie #music #fun'
 '#travel #reels #fitness' '#tech #travel #reels' '#foodie #music #tech'
 '#reels #lifestyle #tech' '#lifestyle #travel #fashion'
 '#fun #love #music' '#lifestyle #tech #fashion' '#tech #fashion #love'
 '#fun #tech #foodie' '#fashion #tech #foodie' '#fun #music #fashion'
 '#tech #fun #lifestyle' '#lifestyle #tech #reels' '#love #reels #fitness'
 '#lifestyle #reels #music' '#fun #tech #fitness' '#tech #love #travel'
 '#reels #fashion #foodie' '#music #foodie #love' '#reels #music'
 '#fashion #fitness #fun' '#lifestyle #music #fun'
 '#lifestyle #reels #foodie' '#music #travel #fitness' '#tech #love #fun'
 '#fashion #foodie #travel' '#fashion #tech #travel' '#tech #reels #music'
 '#tech #lifestyle #foodie' '#reels #travel #love'
 '#fashion #love #foodie' '#reels #fun #fashion' '#reels #fashion #love'
 '#tech #music #love' '#reels #travel #tech' '#fashion #lifestyle #fun'
 '#love #fitness #foodie' '#foodie #love #music' '#reels #fitness #love'
 '#tech #lifestyle' '#lifestyle #fashion #reels' '#tech #foodie #music'
 '#fun #lifestyle #foodie' '#music #fashion #tech'
 '#lifestyle #tech #music' '#love #foodie #lifestyle'
 '#music #foodie #tech' '#lifestyle #fashion #travel'
 '#tech #fashion #music' '#fashion #fun #tech' '#fashion #travel #music'
 '#fashion #fun #lifestyle' '#fitness #fashion #love'
 '#reels #music #love' '#lifestyle #foodie #tech' '#music #fun #travel'
 '#love #fashion #reels' '#lifestyle #love #reels' '#love #travel #reels'
 '#travel #reels #tech' '#lifestyle #fun #tech' '#fitness #travel #foodie'
 '#fitness #fun #reels' '#travel #tech #fitness' '#fashion #reels #fun'
 '#fashion #music #lifestyle' '#love #fitness #lifestyle'
 '#love #lifestyle #foodie' '#music #fun #lifestyle'
 '#foodie #fashion #reels' '#lifestyle #fitness #music'
 '#reels #lifestyle #fitness' '#travel #tech #fun' '#love #travel #music'
 '#music #lifestyle #reels' '#love #tech #travel'
 '#fashion #love #fitness' '#fun #lifestyle #fashion'
 '#foodie #tech #music' '#fashion #fitness' '#fashion #fitness #travel'
 '#music #love #foodie' '#lifestyle #fashion #fun'
 '#music #reels #fitness' '#music #fitness #tech'
 '#reels #foodie #fitness' '#reels #travel #lifestyle' '#love #travel'
 '#fitness #foodie #travel' '#travel #foodie #reels' '#fun #music #tech'
 '#fitness #travel #music' '#travel #fitness #music'
 '#travel #reels #lifestyle' '#fitness #travel #tech'
 '#love #fitness #fashion' '#lifestyle #fashion #fitness'
 '#lifestyle #tech #fun' '#reels #travel #fashion' '#fun #lifestyle #tech'
 '#reels #fitness #music' '#fitness #travel #love'
 '#music #fitness #reels' '#fitness #music' '#reels #lifestyle #foodie'
 '#reels #fashion #fitness' '#lifestyle #fun #love'
 '#fitness #reels #fashion' '#music #reels #tech'
 '#travel #music #lifestyle' '#reels #fashion #travel'
 '#love #fashion #lifestyle' '#fitness #love #foodie'
 '#tech #foodie #reels' '#fashion #travel #foodie' '#tech #fun'
 '#tech #fun #fashion' '#music #fun #foodie' '#lifestyle #fitness #reels'
 '#reels #fitness #fashion' '#music #tech #travel'
 '#reels #fitness #lifestyle' '#reels #tech #love' '#tech #fun #music'
 '#music #lifestyle #fitness' '#reels #fashion #lifestyle'
 '#tech #music #lifestyle' '#tech #lifestyle #fun'
 '#foodie #lifestyle #tech' '#foodie #love' '#reels #music #fashion'
 '#tech #love #foodie' '#tech #fashion #foodie' '#tech #reels #love'
 '#reels #fun #lifestyle' '#travel #fitness #love' '#reels #music #foodie'
 '#foodie #love #fashion' '#tech #fitness #music' '#music #tech #fashion'
 '#love #lifestyle #music' '#foodie #tech #fun'
 '#tech #lifestyle #fitness' '#fun #lifestyle #reels'
 '#reels #travel #foodie' '#love #tech #lifestyle' '#tech #travel #fun'
 '#love #fitness #fun' '#foodie #lifestyle #travel' '#tech #reels #foodie'
 '#lifestyle #love #travel' '#love #fitness #music'
 '#travel #fashion #music' '#fun #fashion #tech' '#foodie #travel'
 '#love #music #fun' '#music #lifestyle #tech' '#fashion #fun #foodie'
 '#tech #foodie #travel' '#tech #travel #lifestyle' '#love #tech #fashion'
 '#foodie #travel #fashion' '#lifestyle #foodie #reels'
 '#tech #fashion #lifestyle' '#fun #fitness #fashion'
 '#travel #fun #foodie' '#love #fitness #reels'
 '#fashion #travel #lifestyle' '#love #foodie #travel'
 '#fun #foodie #travel' '#fashion #lifestyle'
 '#lifestyle #travel #fitness' '#fitness #fashion #fun'
 '#music #fitness #foodie' '#lifestyle #love #foodie'
 '#fun #tech #fashion' '#lifestyle #fitness #love'
 '#fashion #fitness #tech' '#fashion #lifestyle #travel'
 '#fashion #tech #fitness' '#fitness #travel #reels'
 '#fitness #tech #fashion' '#tech #fashion #travel'
 '#tech #foodie #fashion' '#reels #fashion #tech'
 '#music #fashion #fitness' '#lifestyle #fun #travel'
 '#foodie #fitness #fashion' '#fashion #reels #travel'

In [12]:
df["gender"] = df["gender"].astype(str).str.strip().str.lower()

df["gender"] = df["gender"].replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
})
# Check:
df["gender"].value_counts()

gender
Male      1849
other     1581
Female    1570
Name: count, dtype: int64

In [13]:
df["sentiment"] = df["sentiment"].astype(str).str.strip().str.lower()

df["sentiment"] = df["sentiment"].replace({
    "positive": "Positive",
    "negative": "Negative",
    "neutral": "Neutral"
})
# Check:
df["sentiment"].value_counts()

sentiment
Positive    2513
Neutral     1527
Negative     960
Name: count, dtype: int64

In [14]:
# Correct unrealistic engagement values
# For metrics such as likes, comments and shares, negative values are unrealistic.
engagement_cols = ["likes", "comments", "shares"]

for col in engagement_cols:
    df.loc[df[col] < 0, col] = np.nan
    df[col] = df[col].fillna(df[col].median())
# Check:
df[engagement_cols].describe()

              likes     comments     shares
count   5000.000000  5000.000000  5000.0000
mean   10106.997400  1502.039800  1002.9106
std     5702.293017   856.393312   570.8552
min       10.000000     0.000000     0.0000
25%     5235.000000   792.000000   511.0000
50%    10105.500000  1497.000000  1012.0000
75%    14959.000000  2235.250000  1483.0000
max    19998.000000  2999.000000  1999.0000

In [16]:
#['user_id', 'age', 'post_id', 'likes', 'comments', 'shares','watch_time_sec', 'impression_count', 'follower_count','engagement_rate]
engagement_cols1 = ['user_id', 'age', 'post_id',"likes", "comments", "shares",'watch_time_sec', 'impression_count', 'follower_count','engagement_rate']

for col in engagement_cols1:
    df.loc[df[col] < 0, col] = np.nan
    df[col] = df[col].fillna(df[col].median())
# Check:
df[engagement_cols1].describe()

,user_id,age,post_id,likes,comments,shares,watch_time_sec,impression_count,follower_count,engagement_rate
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.0000,5000.000000,5000.000000,5000.000000,5000.000000
mean,54561.890800,38.440400,548042.909000,10106.997400,1502.039800,1002.9106,4014.503200,50013.732800,393698.224800,0.964356
std,26090.370121,14.687151,260646.957267,5702.293017,856.393312,570.8552,2308.096459,28844.939104,230927.884535,5.318029
min,10055.000000,13.000000,100068.000000,10.000000,0.000000,0.0000,0.000000,105.000000,87.000000,0.006363
25%,32309.500000,26.000000,322543.500000,5235.000000,792.000000,511.0000,2017.750000,24988.250000,194480.000000,0.145781
50%,54374.500000,38.000000,548077.500000,10105.500000,1497.000000,1012.0000,4034.500000,49934.500000,388982.000000,0.253896
75%,77180.500000,51.000000,771574.500000,14959.000000,2235.250000,1483.0000,6020.250000,74662.250000,589744.250000,0.504794
max,99963.000000,64.000000,999455.000000,19998.000000,2999.000000,1999.0000,7998.000000,99995.000000,799533.000000,191.504348

In [17]:
# Find outliers using IQR method

columns = [
    "user_id",
    "age",
    "post_id",
    "likes",
    "comments",
    "shares",
    "watch_time_sec",
    "impression_count",
    "follower_count",
    "engagement_rate"
]

for col in columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]

    print(f"\n{col}")
    print("Lower Bound:", lower_bound)
    print("Upper Bound:", upper_bound)
    print("Number of Outliers:", len(outliers))

user_id
Lower Bound: -34997.0
Upper Bound: 144487.0
Number of Outliers: 0

age
Lower Bound: -11.5
Upper Bound: 88.5
Number of Outliers: 0

post_id
Lower Bound: -351003.0
Upper Bound: 1445121.0
Number of Outliers: 0

likes
Lower Bound: -9351.0
Upper Bound: 29545.0
Number of Outliers: 0

comments
Lower Bound: -1372.875
Upper Bound: 4400.125
Number of Outliers: 0

shares
Lower Bound: -947.0
Upper Bound: 2941.0
Number of Outliers: 0

watch_time_sec
Lower Bound: -3986.0
Upper Bound: 12024.0
Number of Outliers: 0

impression_count
Lower Bound: -49522.75
Upper Bound: 149173.25
Number of Outliers: 0

follower_count
Lower Bound: -398416.375
Upper Bound: 1182640.625
Number of Outliers: 0

engagement_rate
Lower Bound: -0.3927378342499999
Upper Bound: 1.04331262375
Number of Outliers: 578

In [18]:
df["engagement_rate"].sort_values(ascending=False).head(10)

554     191.504348
144     121.931973
1947    105.752212
541      92.828829
145      87.266094
4181     77.160173
2369     68.685897
2426     67.511041
652      65.580247
2993     61.179775
Name: engagement_rate, dtype: float64

Outlier Detection: The IQR method was applied to the numerical variables. No significant outliers were detected in user_id, age, post_id, likes, comments, shares, watch_time_sec, impression_count, or follower_count. However, engagement_rate contains statistical outliers that require further investigation for possible data-quality or calculation issues.

# 2.5 Feature Cleaning — Hashtag Count

In [ ]:
# If your dataset has a hashtags column:
def count_hashtags(text):
    if pd.isna(text):
        return 0
    return len(str(text).split())

df["hashtag_count"] = df["hashtags"].apply(count_hashtags)
# If hashtags are stored like:
# travel #india #vacation
# the result will be:
# 3
# Check:
df[["hashtags", "hashtag_count"]].head()

# **Task 3 — Data Exploration using Pandas**

Perform the following:

3.1 View dataset structure using head(), tail(), shape, and columns.

3.2 Check data types and info with info() and dtypes.

3.3 Generate summary statistics using describe().

3.4 Analyze categorical distributions using value_counts(), unique(), and nunique().

3.5 Create a correlation matrix for numeric fields.

3.6 Use groupby() to summarize metrics (e.g., avg likes by post type, impressions by country).

# 3.1 View dataset structure using head(), tail(), shape, and columns.

In [ ]:
# Head
df.head()

In [ ]:
# Tail
df.tail()

In [ ]:
# Shape
df.shape

In [ ]:
# Columns
df.columns

# 3.2 Check data types and info with info() and dtypes.

In [ ]:
# Information
df.info()

In [ ]:
# Data Types
df.dtypes

# 3.3 Generate summary statistics using describe().

In [ ]:
# Summary Statistics
df.describe()

In [ ]:
# For categorical columns:
df.describe(include="object")

In [ ]:
# Post Type
df["post_type"].value_counts()

# 3.4 Analyze categorical distributions using value_counts(), unique(), and nunique().

In [ ]:
# Country
df["country"].value_counts()

In [ ]:
# Sentiment
df["sentiment"].value_counts()

In [ ]:
# Gender
df["gender"].value_counts()

In [ ]:
# Unique values
df["post_type"].unique()

In [ ]:
# Number of unique values
df["post_type"].nunique()

# 3.5 Create a correlation matrix for numeric fields.

In [ ]:
# Correlation Matrix
numeric_df = df.select_dtypes(include=np.number)

correlation = numeric_df.corr()

correlation

# Heat Map

In [ ]:
plt.figure(figsize=(12,8))

sns.heatmap(correlation, annot=True,cmap="coolwarm", fmt=".2f")

plt.title("Correlation Matrix")
plt.show()

# 3.6 Use groupby() to summarize metrics (e.g., avg likes by post type, impressions by country).

In [ ]:
# Average likes by post type
df.groupby("post_type")["likes"].mean().sort_values(ascending=False)

In [ ]:
# Average engagement rate by country
df.groupby("country")["engagement_rate"].mean().sort_values(ascending=False)

In [ ]:
# Average impressions by country
df.groupby("country")["impression_count"].mean().sort_values(ascending=False)

In [ ]:
# Average likes by category
df.groupby("country")["likes"].mean().sort_values(ascending=False)

# **Task 4 — Data Wrangling**

4.1 Use merge, concat, or join if combining DataFrames.

4.2 Create new fields such as engagement_score, log-transformed metrics (optional), and hashtag count.

4.3 Perform groupby summaries by post_type, country, and sentiment.

# 4.1 Use merge, concat, or join if combining DataFrames.

In [ ]:
df1 = df[["post_id", "post_type"]].copy()

df2 = df[["post_id", "likes", "comments", "shares"]].copy()

merged_df = pd.merge(df1, df2, on="post_id", how="inner")

merged_df.head()

# 4.2 Create new fields such as engagement_score, log-transformed metrics (optional), and hashtag count.

In [ ]:
# Create Engagement Score

df["engagement_score"] = (
    df["likes"] +
    df["comments"] +
    df["shares"]
)

In [ ]:
# Create Log-Transformed Metrics

import numpy as np

df["log_likes"] = np.log1p(df["likes"])
df["log_comments"] = np.log1p(df["comments"])
df["log_shares"] = np.log1p(df["shares"])

In [ ]:
# Create Hashtag Count

df["hashtag_count"] = df["hashtags"].fillna("").apply(
    lambda x: len(str(x).split())
)

In [ ]:
# Display new fields

df[[
    "likes",
    "comments",
    "shares",
    "engagement_score",
    "log_likes",
    "log_comments",
    "log_shares",
    "hashtag_count"
]].head()

# 4.3 Perform groupby summaries by post_type, country, and sentiment.

In [ ]:
# GroupBy Summary by Post Type

post_type_summary = df.groupby("post_type").agg({
    "likes": "mean",
    "comments": "mean",
    "shares": "mean",
    "engagement_rate": "mean"
}).sort_values("engagement_rate", ascending=False)

print("Post Type Summary")
display(post_type_summary)

In [ ]:
# GroupBy Summary by Country

country_summary = df.groupby("country").agg({
    "likes": "mean",
    "comments": "mean",
    "shares": "mean",
    "impression_count": "mean",
    "engagement_rate": "mean"
}).sort_values("engagement_rate", ascending=False)

print("Country Summary")
display(country_summary)

In [ ]:
# GroupBy Summary by Sentiment

sentiment_summary = df.groupby("sentiment").agg({
    "likes": "mean",
    "comments": "mean",
    "shares": "mean",
    "impression_count": "mean",
    "engagement_rate": "mean"
}).sort_values("engagement_rate", ascending=False)

print("Sentiment Summary")
display(sentiment_summary)

# **Task 5 — Statistical Analysis**

5. Compute descriptive stats for “likes, comments, shares, watch_time, engagement_rate, followers” columns:

a. Mean, median, mode

b. Standard deviation, variance

c. Percentiles

d. (Optional) Skewness and kurtosis

In [ ]:
stats_cols = [
    "likes",
    "comments",
    "shares",
    "engagement_rate"
]

stats_df = df[stats_cols]

# Mean
mean_values = stats_df.mean()

# Median
median_values = stats_df.median()

# Mode
mode_values = stats_df.mode().iloc[0]

# Standard Deviation
std_values = stats_df.std()

# Variance
variance_values = stats_df.var()

# Percentiles
percentile_25 = stats_df.quantile(0.25)
percentile_50 = stats_df.quantile(0.50)
percentile_75 = stats_df.quantile(0.75)

# Skewness
skewness_values = stats_df.skew()

# Kurtosis
kurtosis_values = stats_df.kurtosis()

# Final summary
summary = pd.DataFrame({
    "Mean": mean_values,
    "Median": median_values,
    "Mode": mode_values,
    "Standard Deviation": std_values,
    "Variance": variance_values,
    "25%": percentile_25,
    "50%": percentile_50,
    "75%": percentile_75,
    "Skewness": skewness_values,
    "Kurtosis": kurtosis_values
})

summary.T

# **Task 6 — Data Visualization**

**6.1 Matplotlib**

○ Scatter: likes vs impressions

○ Line: daily engagement trend

○ Bar: posts by category

○ Pie: gender distribution

○ Histogram: age

○ Box: engagement rate

# 1. Scatter: likes vs impressions

In [ ]:
plt.figure(figsize=(8, 5))

plt.scatter(df["impression_count"], df["likes"], alpha=0.5)

plt.xlabel("Impressions")
plt.ylabel("Likes")
plt.title("Likes vs Impressions")

plt.show()

# Plot 2 — Line Chart: Daily Engagement Trend

In [ ]:
daily_engagement = df.groupby("posted_at")["engagement_score"].mean()

plt.figure(figsize=(12, 5))

plt.plot(daily_engagement.index, daily_engagement.values)

plt.xlabel("Date")
plt.ylabel("Average Engagement Score")
plt.title("Daily Engagement Trend")

plt.xticks(rotation=45)
plt.show()

# Plot 3 — Bar Chart: Posts by Category

In [ ]:
category_counts = df["post_category"].value_counts()

plt.figure(figsize=(10, 5))

plt.bar(category_counts.index, category_counts.values)

plt.xlabel("Category")
plt.ylabel("Number of Posts")
plt.title("Posts by Category")

plt.xticks(rotation=45)
plt.show()

# Plot 4 — Pie Chart: Gender Distribution

In [ ]:
gender_counts = df["gender"].value_counts()

plt.figure(figsize=(7, 7))

plt.pie(
    gender_counts.values,
    labels=gender_counts.index,
    autopct="%1.1f%%"
)

plt.title("Gender Distribution")
plt.show()

# Plot 5 — Histogram: Age

In [ ]:
plt.figure(figsize=(8, 5))

plt.hist(df["age"], bins=20)

plt.xlabel("Age")
plt.ylabel("Frequency")
plt.title("Age Distribution")

plt.show()

# Plot 6 — Box Plot: Engagement Rate

In [ ]:
plt.figure(figsize=(8, 5))

plt.boxplot(df["engagement_rate"].dropna())

plt.ylabel("Engagement Rate")
plt.title("Engagement Rate Distribution")

plt.show()

# **Seaborn Visualizations**

# Plot 7 — Count Plot: Post Type

In [ ]:
plt.figure(figsize=(8, 5))

sns.countplot(data=df, x="post_type")

plt.title("Distribution of Post Types")
plt.xlabel("Post Type")
plt.ylabel("Number of Posts")

plt.xticks(rotation=45)
plt.show()

# Plot 8 — Bar Plot: Average Likes by Category

In [ ]:
plt.figure(figsize=(10, 5))

sns.barplot(
    data=df,
    x="post_category",
    y="likes",
    estimator="mean"
)

plt.title("Average Likes by Category")
plt.xlabel("Category")
plt.ylabel("Average Likes")
plt.xticks(rotation=45)
plt.show()

# Plot 9 — Violin Plot: Followers vs Sentiment

In [ ]:
plt.figure(figsize=(8, 5))

sns.violinplot(
    data=df,
    x="sentiment",
    y="follower_count"
)

plt.title("Followers Distribution by Sentiment")
plt.show()

# Plot 10 — Pair Plot

In [ ]:
pair_cols = [
    "likes",
    "comments",
    "shares",
    "watch_time_sec",
    "engagement_rate"
]

sns.pairplot(df[pair_cols].dropna())

plt.show()

# Plot 11 — Heatmap

In [ ]:
plt.figure(figsize=(12, 8))

sns.heatmap(
    df[numeric_colm].corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")
plt.show()

## Plot 12 — Swarm Plot: Engagement vs Device

In [ ]:
plt.figure(figsize=(10, 6))

sns.swarmplot(
    data=df,
    x="device_type",
    y="engagement_score"
)

plt.title("Engagement Score by Device")
plt.xticks(rotation=45)

plt.show()

# **Plotly Interactive Visualization**

# Interactive Line Chart

In [ ]:
import plotly.express as px

daily_engagement = df.groupby("posted_at",as_index=False)["engagement_rate"].mean()

fig = px.line(
    daily_engagement,
    x="posted_at",
    y="engagement_rate",
    title="Daily Engagement Trend"
)

fig.show()

# **Final Insights**

# **a.Content Performance**

1. Which post types have the highest engagement?

2. Best-performing content category?

3. Which countries have the highest average engagement rate?

In [ ]:
# Post type with highest engagement
post_type_engagement = (
    df.groupby("post_type")["engagement_rate"]
    .mean()
    .sort_values(ascending=False)
)

print(post_type_engagement)
print("Highest:", post_type_engagement.index[0])

In [ ]:
# Best-performing category
category_engagement = (
    df.groupby("post_category")["engagement_rate"]
    .mean()
    .sort_values(ascending=False)
)

print(category_engagement)
print("Highest:", category_engagement.index[0])

In [ ]:
# Countries with highest average engagement
country_engagement = (
    df.groupby("country")["engagement_rate"]
    .mean()
    .sort_values(ascending=False)
)

print(country_engagement.head(10))

# **b.User Trends**

1. How age affects engagement

2. Performance difference for verified accounts

In [ ]:
# Age vs Engagement
# Create age groups:
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 18, 25, 35, 45, 55, 100],
    labels=[
        "Below 18",
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56+"
    ]
)

age_engagement = df.groupby("age_group", observed=False)["engagement_rate"].mean()

print(age_engagement)
# Visualization:
plt.figure(figsize=(9, 5))

sns.barplot(
    x=age_engagement.index,
    y=age_engagement.values
)

plt.xlabel("Age Group")
plt.ylabel("Average Engagement Rate")
plt.title("Engagement Rate by Age Group")

plt.show()

In [ ]:
# Verified vs Non-Verified Accounts

df["follower_count"].value_counts()

verified_analysis = df.groupby("follower_count").agg({
    "likes": "mean",
    "comments": "mean",
    "shares": "mean",
    "engagement_rate": "mean",
    "follower_count": "mean"
})

verified_analysis

# **c.Behavioral Insights**

1. Best time of day for impressions

2. Device type impact on watch time

In [ ]:
hourly_impressions = (
    df.groupby("watch_time_sec")["impression_count"]
    .mean()
    .sort_values(ascending=False)
)

print(hourly_impressions)

print("Highest average impressions hour:",
      hourly_impressions.index[0])

In [ ]:
best_hour = time_analysis.idxmax()
best_impressions = time_analysis.max()

print("Best hour:", best_hour)
print("Average impressions:", round(best_impressions, 2))

In [ ]:
import matplotlib.pyplot as plt
device_watch = (
    df.groupby("device_type")["watch_time_sec"]
    .mean()
    .sort_values(ascending=False)
)

print(device_watch)

# **d. Sentiment Analysis**

1. Which sentiment performs best

2. Behavior of negative/neutral sentiment posts

In [ ]:
# Which sentiment performs best?
sentiment_performance = (
    df.groupby("sentiment").agg({
        "likes": "mean",
        "comments": "mean",
        "shares": "mean",
        "engagement_rate": "mean",
        "impression_count": "mean"
    })
)

sentiment_performance
# You can specifically compare:
sentiment_engagement = (
    df.groupby("sentiment")["engagement_rate"]
    .mean()
    .sort_values(ascending=False)
)

print(sentiment_engagement)

In [ ]:
# Negative vs Neutral Sentiment Behavior
df["sentiment"] = df["sentiment"].astype(str).str.strip().str.lower()

negative_neutral = df[
    df["sentiment"].isin(["negative", "neutral"])
]

sentiment_behavior = negative_neutral.groupby("sentiment").agg({
    "likes": "mean",
    "comments": "mean",
    "shares": "mean",
    "impression_count": "mean",
    "engagement_rate": "mean"
}).round(2)

sentiment_behavior